// Shared constants for dropdown selections across the application

export const JOB_ROLES = [
  "Chief Executive Officer (CEO)",
  "Chief Technology Officer (CTO)",
  "Chief Financial Officer (CFO)",
  "Chief Marketing Officer (CMO)",
  "Chief Operating Officer (COO)",
  "Chief of Staff",
  "Vice President",
  "Director",
  "Senior Manager",
  "Manager",
  "Team Lead",
  "Project Manager",
  "Product Manager",
  "Software Engineer",
  "Data Analyst",
  "Business Analyst",
  "Sales Executive",
  "Marketing Specialist",
  "Human Resources Specialist",
  "Customer Support Representative",
  "Other",
];

export const INDUSTRIES = [
  "Technology",
  "Finance",
  "Healthcare",
  "Education",
  "Manufacturing",
  "Retail",
  "Transportation",
  "Energy",
  "Telecommunications",
  "Media & Entertainment",
  "Real Estate",
  "Construction",
  "Agriculture",
  "Government",
  "Nonprofit",
  "Professional Services",
  "Insurance",
  "Automotive",
  "Pharmaceuticals",
  "Other",
];

export const COMPANY_SIZES = [
  { value: "1", label: "Sole Proprietor (1)" },
  { value: "2-9", label: "Small Team (2-9)" },
  { value: "10-49", label: "Small Business (10-49)" },
  { value: "50-249", label: "Medium Business (50-249)" },
  { value: "250-999", label: "Large Business (250-999)" },
  { value: "1000-9999", label: "Enterprise (1,000-9,999)" },
  { value: "10000+", label: "Large Enterprise (10,000+)" },
];

export const COUNTRIES = [
  "Albania",
  "Andorra",
  "Australia",
  "Austria",
  "Belarus",
  "Belgium",
  "Bosnia and Herzegovina",
  "Brazil",
  "Bulgaria",
  "Canada",
  "China",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Iceland",
  "India",
  "Ireland",
  "Italy",
  "Japan",
  "Kosovo",
  "Latvia",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Mexico",
  "Moldova",
  "Monaco",
  "Montenegro",
  "Netherlands",
  "New Zealand",
  "North Macedonia",
  "Norway",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "San Marino",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vatican City",
];
