/** Administrator-only material for the Information Security course package. */
import type { AdminSpec } from "../shared/admin-docs";

export const admin: AdminSpec = {
  courseId: "SYN-SEC-2026",
  sourceVersion: "0.1 draft, prepared September 23, 2026, for policy-owner review",
  sourceSlides: [
    { n: 1, title: "Cover: Information Security (Recognize, Protect, Report)", treatment: "Motif reused in the course hero and objectives. Course ID and version kept in this package, not shown to learners." },
    { n: 2, title: "Course objectives", treatment: "Rewritten as learner outcomes; scope and role-specific training notes expanded into their own slide." },
    { n: 3, title: "LEARN 01: Protect information in daily work", treatment: "Confidentiality, integrity, and availability table with everyday examples from the notes; reflection prompt kept." },
    { n: 4, title: "LEARN 02: Protect your sign-in", treatment: "Split into three slides (identity, MFA prompts, least privilege). No new password-length rule, per the notes." },
    { n: 5, title: "LEARN 03: Verify before you act", treatment: "Split into channels, an annotated fictional message, the pause/verify/report diagram, and an independent-verification table." },
    { n: 6, title: "LEARN 04: Use approved tools and AI", treatment: "Two slides; refers learners to the current IT Policy instead of freezing a product list. Hidden-instruction warning kept." },
    { n: 7, title: "LEARN 05: Secure devices wherever you work", treatment: "Three slides (devices, workspace, lost equipment) with the remote-work photo." },
    { n: 8, title: "LEARN 06: Share through the approved route", treatment: "Three slides (share check, blocked route, suspected CUI) with the collaboration photo. CUI is not equated with all confidential data." },
    { n: 9, title: "LEARN 07: Report incidents immediately", treatment: "What to report, the employee/responder boundary graphic, and reporting routes. Security issues go to security@synozur.com; urgent or after-hours security incidents use the confirmed 24-hour route ITHelp@synozur.com; normal IT help and general support remain separate." },
    { n: 10, title: "LEARN 08: Notice misuse without making assumptions", treatment: "Observable behaviors and a do/don’t table; no profiling." },
    { n: 11, title: "Practice scenario: the urgent support call", treatment: "Native practice quiz with three questions and feedback (not graded). Facilitator guidance became the feedback." },
    { n: 12, title: "Review question Q01", treatment: "Final knowledge check Q1; wording, choice order, and intended answer retained." },
    { n: 13, title: "Review question Q02", treatment: "Final knowledge check Q2; wording, choice order, and intended answer retained." },
    { n: 14, title: "Review question Q03", treatment: "Final knowledge check Q3; wording, choice order, and intended answer retained." },
    { n: 15, title: "Review question Q04", treatment: "Final knowledge check Q4; wording, choice order, and intended answer retained." },
    { n: 16, title: "Review question Q05", treatment: "Final knowledge check Q5; wording, choice order, and intended answer retained." },
    { n: 17, title: "Proposed acknowledgement wording", treatment: "Native typed-name attestation with the wording preserved verbatim. Clarification guidance moved to the preceding “Before you sign” lesson." },
    { n: 18, title: "Administrator guidance (appendix)", treatment: "Admin only. Release gates are in the approval checklist. The outdated note that Orion import and attestation behavior are unverified is superseded; see “Orion capabilities verified”." },
    { n: 19, title: "Framework mapping (appendix)", treatment: "Admin only; reproduced in the framework mapping section below. Informs the course-scope slide and Q5/Q8." },
    { n: 20, title: "References", treatment: "Learner-safe subset in the optional “Policies and sources” lesson." },
  ],
  frameworkMapping: [
    "NIST CSF 2.0 PR.AT-01: personnel receive awareness and training to perform general tasks with security risks in mind (whole course).",
    "NIST CSF 2.0 PR.AT-02: individuals in specialized roles receive training (course states that role-specific training is separate; Q8).",
    "NIST CSF 2.0 GV.PO-01: policy is established, communicated, and enforced (policy links and the attestation).",
    "NIST SP 800-171 Rev. 2, 3.2.1–3.2.3, and Rev. 3, 03.02.01–03.02.02 (awareness and role-based training, including insider-threat awareness): applicable only where a contract brings CUI into scope; the governing revision must be confirmed.",
    "This course supports awareness and training evidence only. It does not establish certification or show that controls are implemented.",
  ],
  approvals: [
    { item: "Confirm the policy owner or designated contact for attestation questions", where: "Lesson 5.2 (Before you sign)", owner: "Policy owner", blocker: true },
    { item: "Policy-owner review of all learner content and the attestation wording", where: "Whole course; lesson 5.3", owner: "Policy owner", blocker: true },
    { item: "Confirm the Security Policy’s approval and effective status, and the final links for both policies", where: "Lessons 5.2 and 6.1", owner: "Policy owner", blocker: true },
    { item: "Welcome video: record, upload to the empty video block, remove the poster image block, replace the draft transcript, and verify captions (or approve a transcript-only launch)", where: "Lesson 1.1", owner: "Chris McNulty / course author", blocker: true },
    { item: "Narration: review each script, mark approved, and generate audio with the approved Azure Speech voice (or approve transcript-only narration)", where: "All slide lessons", owner: "Course author", blocker: false },
    { item: "Confirm NIST scope: governing standard and revision, assessment boundary, and whether any contract brings CUI into scope", where: "Lessons 1.2, 3.3, 6.1; Q5", owner: "Security owner / contracts", blocker: false },
    { item: "Identify who needs role-specific training (administrators, developers, incident responders, data owners) and how it is assigned", where: "Lesson 1.2; Q8", owner: "Security owner", blocker: false },
    { item: "Approve the pass rule: 85% on the equally weighted eight-question final check (at least 7/8 correct, or 87.5%) with unlimited retries; remediation before retry is recommended in feedback but not enforced", where: "Lesson 5.1", owner: "Policy owner", blocker: false },
    { item: "Approve the estimated duration (about 25 minutes including narration) against the 15–20 minute default", where: "Whole course", owner: "Policy owner", blocker: false },
    { item: "Confirm retention and access rules for attestation records", where: "Attestation records", owner: "Policy owner / security owner", blocker: false },
    { item: "Keep completion certificates disabled until approved; any certificate must describe course completion, not certification", where: "Course settings", owner: "Policy owner", blocker: false },
    { item: "Approve the graphics and the two CC0 stock photos, or supply approved Synozur photography", where: "Hero, poster, lessons 2.2, 2.3, 3.1, 3.3, 4.1", owner: "Brand owner", blocker: false },
    { item: "Production target for a later, separately authorized release: Synozur.com. Keep drafts private; this package update does not authorize or perform a production import, publish, or learner enrollment", where: "Future production release", owner: "Orion administrator", blocker: false },
    { item: "Use Synozur Test as the confirmed development owner for non-production testing. Any production pilot with real learner accounts in Synozur.com requires separate release authorization; no production pilot or enrollment is part of this work", where: "Development testing / future production release", owner: "Orion administrator", blocker: false },
  ],
  recordingGuidance: [
    "Record Chris McNulty on camera using the supplied script; do not synthesize his face or voice.",
    "Aim for 60–90 seconds in a quiet, well-lit setting. Keep client names, screens, and documents out of frame.",
    "Export MP4 (H.264, 1080p) and upload it to the empty video block on the lesson’s only slide. Then remove the “coming soon” poster image block (the poster is already set on the video block).",
    "Replace the draft transcript with a final transcript that matches the recording word for word.",
    "Orion video blocks don’t support caption tracks yet. Keep the final transcript on the slide, and either approve a transcript-only launch or burn corrected captions into the video.",
    "When the video is live, decide whether the lesson should become required (it is optional now so the placeholder is never counted as watched).",
  ],
  courseSpecificLimitations: [
    "Per-choice feedback exists only in this package. Orion shows one explanation per question, so explanations cover the tempting wrong choices and name the lesson to revisit without naming the correct option.",
    "Practice quizzes use a passing score of 0, so Orion’s result banner says “Passed!” and “Passing 0” after any attempt. The introduction states that practice isn’t graded.",
  ],
};
