/** Administrator-only source mapping and release gates for business conduct. */
import type { AdminSpec } from "../shared/admin-docs";

export const admin: AdminSpec = {
  courseId: "SYN-CON-2026",
  sourceVersion: "0.1 draft, prepared September 23, 2026, for policy-owner review",
  sourceSlides: [
    { n: 1, title: "Cover: Standards of Business Conduct", treatment: "Title and decision-test motif carried into hero; draft status retained in release gates." },
    { n: 2, title: "Course objectives", treatment: "Conflict, accuracy, and speak-up outcomes shape lessons 1.2–4.4." },
    { n: 3, title: "LEARN 01: Use a consistent decision test", treatment: "Expanded permission, honesty, fairness, authority, explainability; marked proposed." },
    { n: 4, title: "LEARN 02: Disclose conflicts before acting", treatment: "Disclosure and recusal diagram with complete text equivalent; management safeguards remain proposed." },
    { n: 5, title: "LEARN 03: Do not trade favors for business", treatment: "Offers, timing, transparency, and honest expenses; no unverified threshold." },
    { n: 6, title: "LEARN 04: Keep records and claims accurate", treatment: "Synthetic correction graphic, signing authority, and verified claims; no certification assertion." },
    { n: 7, title: "LEARN 05: Respect people in every setting", treatment: "Respectful-workplace lesson and colleague-response question; pending HR/legal approval." },
    { n: 8, title: "LEARN 06: Protect client trust and intellectual property", treatment: "Permissions, licensing, confidentiality, and competition guidance." },
    { n: 9, title: "LEARN 07: Take responsibility for tools and partners", treatment: "Human review of AI content, partner approval, and accountable assurance claims." },
    { n: 10, title: "LEARN 08: Raise concerns without retaliation", treatment: "Reporting-route diagram and text equivalent include the specified ReportIt@synozur.com code-of-conduct breach route; usual and alternate contacts remain release blockers." },
    { n: 11, title: "Practice: a favor during selection", treatment: "Expanded fictional ungraded supplier scenario; facilitator guidance informs feedback." },
    { n: 12, title: "Review question Q01", treatment: "Final Q1; source stem, choices, order and intended answer A preserved." },
    { n: 13, title: "Review question Q02", treatment: "Final Q2; source stem, choices, order and intended answer D preserved." },
    { n: 14, title: "Review question Q03", treatment: "Final Q3; source stem, choices, order and intended answer B preserved." },
    { n: 15, title: "Review question Q04", treatment: "Final Q4; source stem, choices, order and intended answer C preserved." },
    { n: 16, title: "Review question Q05", treatment: "Final Q5; source stem, choices, order and intended answer A preserved." },
    { n: 17, title: "Proposed annual acknowledgement", treatment: "Verbatim typed-name attestation after separate Before you sign lesson; clarification leaves it unsigned." },
    { n: 18, title: "Administrator release guidance", treatment: "Administrator only; obsolete claims that Orion import is unverified replaced by build documentation; approval gates below." },
    { n: 19, title: "Indicative framework mapping", treatment: "Administrator-only qualified security-governance mapping below; no whole-course NIST mapping." },
    { n: 20, title: "References and policy precedence", treatment: "Learner-safe links in optional Reference module; policy approval and contract scope pending." },
  ],
  frameworkMapping: [
    "NIST CSF 2.0 GV.RR-01, GV.RR-02, GV.PO-01 and GV.RR-04 can inform security-related governance, workforce roles, and policy communication only. This mapping does not cover the whole business-conduct curriculum: gifts, conflicts, anti-bribery, respect, and fair competition extend beyond cybersecurity.",
    "NIST Privacy Framework 1.0 concerns privacy risk governance, not an ethics code or a substitute for NIST CSF 2.0.",
    "NIST SP 800-171 Rev. 3 awareness and training requirements concern protected CUI in applicable contract scope; confirm governing revision and contract. Not all confidential client information is CUI.",
    "Training and attestation are awareness evidence only; neither establishes control implementation, an assessed compliance boundary, nor organizational certification.",
  ],
  approvals: [
    { item: "Approve the Standards of Business Conduct as adopted guidance, or revise every proposed conduct statement; confirm policy scope and effective status", where: "Whole course; lessons 1.2, 5.2, 6.1 and PDF", owner: "Conduct policy owner / legal / HR", blocker: true },
    { item: "Verify designated conduct/ethics reporting contact and approved usual route; the specified ReportIt@synozur.com route is for code-of-conduct breaches only", where: "Lessons 2.1, 4.3–4.4 and PDF", owner: "Conduct policy owner / HR", blocker: true },
    { item: "Verify an independent designated alternate reporting route if the usual contact is involved or uncomfortable to use, and verify the HR contact", where: "Lessons 4.3–4.4 and PDF", owner: "HR / legal", blocker: true },
    { item: "Approve gift and hospitality rules, restrictions, approvals and client/public-sector exceptions; no monetary threshold is implied", where: "Lessons 2.1–2.3; PDF", owner: "Conduct policy owner / legal", blocker: true },
    { item: "After gift rules and reporting routes are approved, update the recusal and reporting diagrams: remove proposed/pending badges, name the approved routes, re-render both images, and update their text equivalents to match", where: "Lessons 2.1 and 4.3; recuse and routes graphics", owner: "Conduct policy owner / course author", blocker: true },
    { item: "Approve investigation language, fair process and non-retaliation protections; confirm wording preserving lawful external reporting rights without promising anonymity", where: "Lesson 4.3; reporting reference; welcome script", owner: "HR / legal", blocker: true },
    { item: "Approve exact verbatim deck attestation wording against the adopted standards, and designate an accountable contact for attestation questions", where: "Lessons 5.2–5.3; reference PDF", owner: "Policy owner / HR / legal", blocker: true },
    { item: "Welcome video: confirm the script's reporting and non-retaliation statements against the approved code before recording or launch; record Chris, upload real video, verify corrected captions and final transcript or explicitly approve transcript-only launch", where: "Lesson 1.1", owner: "Chris McNulty / conduct policy owner / HR / legal", blocker: true },
    { item: "Confirm Security Policy approval/effective status and final IT/Security Policy links; keep IT requirements distinct from proposed conduct standards", where: "Lessons 1.2, 5.2, 6.1", owner: "IT / security policy owner", blocker: true },
    { item: "Resolve remaining reporting and approval placeholders; re-render draft decision-and-reporting PDF from DECISION_REFERENCE and remove DRAFT watermark/banner only after all remaining details are verified", where: "Lesson 4.4; course resource", owner: "Course author / conduct policy owner", blocker: true },
    { item: "Approve narration scripts and use configured Azure Speech voice; do not overwrite existing audio without confirmation", where: "All slide lessons", owner: "Course author", blocker: false },
    { item: "Approve 100% final check with retries; suggested remediation cannot be enforced before retry", where: "Lesson 5.1", owner: "Conduct policy owner", blocker: false },
    { item: "Confirm NIST assessment scope, framework versions, applicable contract and CUI scope before any external assurance statement", where: "Lessons 3.2 and 6.1; framework mapping", owner: "Security / contracts owner", blocker: false },
    { item: "Approve hero, poster, diagrams and CC0 photos; verify photo credits and rights before build or launch", where: "Media in lessons 1.1–4.3", owner: "Brand / course owner", blocker: true },
    { item: "Confirm access and retention of attestation records and the process for unsigned clarification requests", where: "Lessons 5.2–5.3", owner: "HR / security", blocker: false },
    { item: "Keep draft tenant-private; no certificate or automatic annual renewal is implied", where: "Course settings", owner: "Orion administrator", blocker: false },
  ],
  recordingGuidance: [
    "Confirm the welcome script's reporting and non-retaliation statements against the approved code with the conduct policy owner and HR/legal before recording or launch. The current wording is draft.",
    "Record Chris McNulty reading the supplied script; do not synthesize his face or voice. Avoid confidential screens or documents.",
    "Upload the finished H.264 MP4 into the empty video block; remove the duplicate poster image once video is present.",
    "Replace the draft transcript with a corrected transcript matching the recording. Video blocks do not support separate caption tracks; provide corrected burned-in captions or explicitly approve transcript-only launch.",
    "The placeholder is optional and not counted as watched; decide whether to require the lesson only after the recording exists.",
  ],
  courseSpecificLimitations: [
    "Proposed conduct standards beyond the retrieved IT policies have no verified approval. The specified ReportIt@synozur.com route applies to code-of-conduct breaches; designated usual and independent alternate contacts, HR contact, gift limits, investigation wording, and attestation approval remain release blockers.",
    "Per-choice feedback, question origin, and revisit targets remain administrator-only; Orion displays one post-submission explanation per question.",
    "Practice passing score 0 can produce a Passed banner despite being ungraded; introductions explain the distinction.",
    "The empty video slot has no recording; Orion may still let a learner mark this optional lesson complete.",
    "An unsigned attestation remains incomplete; Orion has no native clarification choice, so a verified owner must handle questions outside the training response.",
  ],
};