import { beforeEach, describe, expect, it, vi } from "vitest";

const { storageMock, dbMock } = vi.hoisted(() => ({
  storageMock: {
    getModel: vi.fn(),
    getDimensionsByModelId: vi.fn(),
    getQuestionsByModelId: vi.fn(),
  },
  dbMock: {
    select: vi.fn(() => ({
      from: vi.fn(() => ({
        where: vi.fn(() => ({
          orderBy: vi.fn().mockResolvedValue([]),
        })),
      })),
    })),
  },
}));

vi.mock("../../server/storage", () => ({ storage: storageMock }));
vi.mock("../../server/db", () => ({ db: dbMock }));

import { exportInterviewGuide } from "../../server/services/model-export-service";

describe("exportInterviewGuide", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    storageMock.getDimensionsByModelId.mockResolvedValue([]);
    storageMock.getQuestionsByModelId.mockResolvedValue([]);
  });

  it("includes the configured scoring scale at the bottom", async () => {
    storageMock.getModel.mockResolvedValue({
      id: "model-1",
      name: "Maturity Assessment",
      description: "Assess maturity.",
      estimatedTime: "15 minutes",
      maturityScale: [
        {
          id: "beginner",
          name: "Beginner",
          description: "Starting out",
          minScore: 0,
          maxScore: 39,
        },
        {
          id: "advanced",
          name: "Advanced",
          description: "Leading practice",
          minScore: 70,
          maxScore: 100,
        },
      ],
    });

    const { markdown } = await exportInterviewGuide("model-1");

    expect(markdown).toContain("## Scoring Scale");
    expect(markdown).toContain("| Beginner | 0–39 | Starting out |");
    expect(markdown).toContain("| Advanced | 70–100 | Leading practice |");
    expect(markdown.indexOf("## Scoring Scale")).toBeLessThan(markdown.indexOf("*Generated by Orion"));
  });

  it("uses the default scale when the model has no configured scale", async () => {
    storageMock.getModel.mockResolvedValue({
      id: "model-1",
      name: "Legacy Assessment",
      description: "",
      maturityScale: null,
    });

    const { markdown } = await exportInterviewGuide("model-1");

    expect(markdown).toContain("| Nascent | 100–199 | Beginning AI journey |");
    expect(markdown).toContain("| Transformational | 450–500 | Leading AI transformation |");
  });
});