/** Administrator-only release and source mapping for the privacy course. */
import type { AdminSpec } from "../shared/admin-docs";

export const admin: AdminSpec = {
  courseId: "SYN-PRI-2026",
  sourceVersion: "0.1 draft, prepared September 23, 2026, for policy-owner review",
  sourceSlides: [
    { n: 1, title: "Cover: Data Privacy and Client Confidentiality", treatment: "Theme and outcomes carried into the course hero, welcome, and distinction lesson; course ID remains administrator-only." },
    { n: 2, title: "Course objectives", treatment: "Three outcomes inform the sequence; training is not certification or legal advice." },
    { n: 3, title: "LEARN 01: Privacy and confidentiality work together", treatment: "Overlap graphic and a separate secure-but-unauthorized-use example; note distinctions retained." },
    { n: 4, title: "LEARN 02: Collect for a clear purpose", treatment: "Task-first guidance and a fictional before-and-after minimization graphic; residual identification risk explained." },
    { n: 5, title: "LEARN 03: Respect the data classification", treatment: "Client labels, need-to-know, separate workspaces, and uncertainty escalation; no invented taxonomy." },
    { n: 6, title: "LEARN 04: Check every disclosure", treatment: "Separated sharing checks and meeting/recording access; NDA and hidden-content notes retained." },
    { n: 7, title: "LEARN 05: AI and vendors need boundaries", treatment: "Service, account, data-flow, client restrictions, and output review; new-use/vendor review retained." },
    { n: 8, title: "LEARN 06: Keep only what is required", treatment: "Lifecycle graphic and legal-hold caveat; schedule and process remain placeholders for approval." },
    { n: 9, title: "LEARN 07: Route privacy requests promptly", treatment: "Request routing and responsible-owner assessment; no universal deadlines or legal applicability claims." },
    { n: 10, title: "LEARN 08: Treat accidental disclosure as an incident", treatment: "Urgent security incidents route to ITHelp@synozur.com (24-hour route); other security issues to security@synozur.com; privacy concerns/questions to privacy@synozur.com." },
    { n: 11, title: "Practice: reuse a client example", treatment: "Expanded fictional ungraded AI-transcript scenario with unique project and pricing still present; source facilitator guidance became feedback." },
    { n: 12, title: "Review question Q01", treatment: "Final check Q1; source wording and choice order preserved." },
    { n: 13, title: "Review question Q02", treatment: "Final check Q2; source wording and choice order preserved." },
    { n: 14, title: "Review question Q03", treatment: "Final check Q3; source wording and choice order preserved." },
    { n: 15, title: "Review question Q04", treatment: "Final check Q4; source wording and choice order preserved." },
    { n: 16, title: "Review question Q05", treatment: "Final check Q5; source wording and choice order preserved." },
    { n: 17, title: "Proposed annual acknowledgement", treatment: "Verbatim native typed-name statement, preceded by a separate Before you sign lesson. Clarification leaves attestation unsigned." },
    { n: 18, title: "Administrator release guidance", treatment: "Administrator only. Release blockers below; obsolete Orion feature uncertainty superseded by current build capabilities." },
    { n: 19, title: "Indicative framework mapping", treatment: "Administrator-only educational mapping below, not a certification claim." },
    { n: 20, title: "References and policy precedence", treatment: "Learner-safe policy/framework links in optional Reference lesson; approval status still pending." },
  ],
  frameworkMapping: [
    "NIST Privacy Framework 1.0 GV.AT-P: roles, responsibilities, and awareness (whole course).",
    "NIST Privacy Framework 1.0 ID.IM-P, CT.PO-P, CT.DM-P: purpose, data handling, requests, and disposal (lessons 2.1, 4.1–4.3).",
    "NIST Privacy Framework 1.0 PR.DS-P and GV.PO-P; NIST CSF 2.0 GV.OC-03 and PR.AT-01: protection, client obligations, and training awareness.",
    "SP 800-171 is not a general privacy law. CUI scope and governing revision depend on applicable contracts; confirm scope before asserting relevance.",
    "Educational alignment and training evidence only. The course does not establish legal applicability, control implementation, certification, or organizational compliance.",
  ],
  approvals: [
    { item: "Approve the retention schedule by record type, including recordings and working copies", where: "Lesson 4.1; Before you share PDF", owner: "Records / policy owner", blocker: true },
    { item: "Confirm the legal-hold process and contact, including handling a deletion request during a hold", where: "Lessons 4.1–4.4; Before you share PDF", owner: "Legal / records owner", blocker: true },
    { item: "Confirm client-specific requirements and engagement-owner route for classification, AI, recordings, and reuse", where: "Lessons 2.2, 3.1–3.2, 4.4, 5.2; Before you share PDF", owner: "Engagement / contracts owner", blocker: true },
    { item: "Confirm route for access, correction, deletion, and restriction requests, with client coordination", where: "Lessons 4.2 and 4.4; Before you share PDF", owner: "Privacy / legal owner", blocker: true },
    { item: "Confirm contact for attestation clarification questions", where: "Lesson 5.2", owner: "Policy owner / legal", blocker: true },
    { item: "Resolve placeholders, remove DRAFT marking, and re-render and upload PDF after contact and route verification", where: "Before you share course resource", owner: "Course author / privacy owner", blocker: true },
    { item: "Policy-owner and legal review of proposed retention, request, incident, and legal-hold guidance and exact source attestation wording", where: "Whole course; lesson 5.3", owner: "Policy owner / legal", blocker: true },
    { item: "Verify access to the IT Policies page and Active Policy Library, then confirm the current IT revision and Security Policy document, approval, and effective status", where: "Lessons 5.2 and 6.1", owner: "Policy owner", blocker: true },
    { item: "Record Chris’s welcome, upload it into the empty video block, remove the separate poster image, verify corrected captions and final transcript, or explicitly approve transcript-only launch", where: "Lesson 1.1", owner: "Chris McNulty / course author", blocker: true },
    { item: "Review slide narration scripts and approve/generate audio with the configured Azure Speech voice; do not replace existing audio without confirmation", where: "All slide lessons", owner: "Course author", blocker: false },
    { item: "Approve 85% final check (which requires at least 7/8 correct, or 87.5%, on eight equally weighted questions) with unlimited retries; explanations recommend remediation but Orion cannot require it before retry", where: "Lesson 5.1", owner: "Policy owner", blocker: false },
    { item: "Confirm governing NIST standard/revision, assessment boundary, contract, and any CUI scope before compliance claims", where: "Lessons 1.2 and 6.1; framework mapping", owner: "Security / contracts owner", blocker: false },
    { item: "Approve the overlap, lifecycle, minimization illustrations and CC0 document-review and workshop photos; or replace with approved Synozur assets", where: "Hero, poster, lessons 1.2, 2.1, 3.1, 4.1", owner: "Brand owner", blocker: false },
    { item: "Confirm access and retention of signed attestation records", where: "Lessons 5.2–5.3", owner: "Policy owner / privacy owner", blocker: false },
    { item: "Keep certificates disabled and course tenant-private until release; operational annual enrollment and communication are separate", where: "Course settings", owner: "Orion administrator", blocker: false },
  ],
  recordingGuidance: [
    "Record Chris McNulty reading the supplied script; do not synthesize his face or clone his voice. Keep client names, screens, and records out of frame.",
    "Use a quiet, well-lit setting; export a 1080p H.264 MP4 to the empty video block. Remove the extra poster image when the video is ready (the slot already has posterMedia).",
    "Replace the draft transcript with a corrected transcript matching the recording. Orion video blocks do not currently support caption tracks: burn corrected captions into the video or explicitly approve a transcript-only launch.",
    "The placeholder lesson remains optional so it does not count as watched. Decide whether it becomes required after recording is in place.",
  ],
  courseSpecificLimitations: [
    "Per-choice feedback, revisit targets, and question sources are administrator-only. Orion shows one learner explanation per question after submission.",
    "Passing score 0 allows ungraded practice, but Orion may still show a “Passed!” banner; each practice introduction clearly identifies it as not graded.",
    "The video slot is empty until a real recording is uploaded; the lesson is optional, though Orion may still allow a learner to mark it complete.",
    "No legal deadlines, blanket consent rules, retention periods, or universal statute applicability are claimed. Responsible privacy, legal, client, and record owners must assess the facts.",
  ],
};